
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: samantha
    password: TaskManager2025
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


